dbt_pipelines:
  outputs:
    dev:
      type: duckdb
      path: /shared/dev.duckdb
      extensions:
        - httpfs
        - parquet
        - iceberg
      secrets:
        - type: s3
          region: "{{ env_var('AWS_DEFAULT_REGION') }}"
          key_id: "{{ env_var('AWS_ACCESS_KEY_ID') }}"
          secret: "{{ env_var('AWS_SECRET_ACCESS_KEY') }}"

          client_kwargs:
            endpoint_url: "{{ env_var('ENDPOINT_URL') }}"
      threads: 1

    prod:
      type: duckdb
      path: /shared/prod.duckdb
      extensions:
        - httpfs
        - parquet
        - iceberg
      secrets:
        - type: s3
          region: "{{ env_var('AWS_DEFAULT_REGION') }}"
          key_id: "{{ env_var('AWS_ACCESS_KEY_ID') }}"
          secret: "{{ env_var('AWS_SECRET_ACCESS_KEY') }}"

          client_kwargs:
            endpoint_url: "{{ env_var('ENDPOINT_URL') }}"
      threads: 4

  target: dev
